version: "3.1"
services:
  developer-node:
    build: ./node
    image: developer.mach.org.ua_node_image
    container_name: developer.mach.org.ua_node
    user: ${CURRENT_UID}:${CURRENT_GID}
    volumes:
      - "./..:/code"
    working_dir: /code
    env_file:
      - ./node/.env
    tty: true
    stdin_open: true
  developer-nginx:
    image: nginx:alpine
    container_name: developer.mach.org.ua_nginx
    volumes:
      - "./..:/var/www"
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    expose:
      - 80
    links:
      - developer-php-fpm
    env_file:
      - ./nginx/.env
  api-developer-nginx:
    image: nginx:alpine
    container_name: api.developer.mach.org.ua_nginx
    volumes:
      - "./..:/var/www"
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    expose:
      - 80
    links:
      - developer-php-fpm
    env_file:
      - ./nginx/.api.env
  developer-php-fpm:
    build:
      context: ./php-fpm
      args:
        uid: ${CURRENT_UID}
    image: developer.mach.org.ua_php_image:1.0.1
    container_name: developer.mach.org.ua_php
    user: ${CURRENT_UID}:${CURRENT_GID}
    volumes:
      - "./..:/var/www"
    working_dir: /var/www
    links:
      - developer-db
  developer-db:
    image: mysql:5.7
    container_name: developer.mach.org.ua_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "./db/logs/mysql-slow.log:/var/log/mysql/mysql-slow.log"
    env_file:
      - ./db/.env
    ports:
      - "3307:3306"

networks:
  default:
    external:
      name: nginx-proxy