version: "3.1"
services:
  developer-node:
    build: ./node
    image: developer.mach.org.ua_node_image
    container_name: developer.mach.org.ua_node
    volumes:
      - "./..:/code"
    working_dir: /code
    tty: true
    stdin_open: true
  developer-nginx:
    image: nginx:alpine
    container_name: developer.mach.org.ua_nginx
    volumes:
      - "./..:/var/www"
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    expose:
      - 80
    links:
      - developer-php-fpm
    environment:
      VIRTUAL_HOST: developer.mach.org.ua
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: developer.mach.org.ua
      LETSENCRYPT_EMAIL: admin@developer.mach.org.ua
  api-developer-nginx:
      image: nginx:alpine
      container_name: api.developer.mach.org.ua_nginx
      volumes:
        - "./..:/var/www"
        - "./nginx/logs:/var/log/nginx"
        - "./nginx/conf.d:/etc/nginx/conf.d"
      expose:
        - 80
      links:
        - developer-php-fpm
      environment:
        VIRTUAL_HOST: api.developer.mach.org.ua
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: api.developer.mach.org.ua
        LETSENCRYPT_EMAIL: api.admin@developer.mach.org.ua
  developer-php-fpm:
    build: ./php-fpm
    image: developer.mach.org.ua_php_image
    container_name: developer.mach.org.ua_php
    volumes:
      - "./..:/var/www"
    working_dir: /var/www
    links:
      - developer-db
  developer-db:
    image: mysql:5.7
    container_name: developer.mach.org.ua_db
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "./db/logs/mysql-slow.log:/var/log/mysql/mysql-slow.log"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: dopusk_local
    secrets:
      - db_password
      - db_name

secrets:
  db_password:
    file: ./db/secrets/db_password.txt
  db_name:
    file: ./db/secrets/db_name.txt

networks:
  default:
    external:
      name: nginx-proxy